# Generated by Django 6.1 on 2026-08-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان فیلم')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='movies/%Y/%m', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('Release_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('actors', models.ManyToManyField(related_name='actors', to='categories.actorsmodel', verbose_name=' بازیگران')),
                ('directors', models.ManyToManyField(related_name='directors', to='categories.directormodel', verbose_name='کارگردان')),
                ('genres', models.ManyToManyField(related_name='genres', to='categories.genremodel', verbose_name='ژانرها')),
            ],
            options={
                'verbose_name': 'فیلم و سریال',
                'verbose_name_plural': 'فیلم و سریال ها',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MovieVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='movies/%Y/%m')),
                ('is_trailer', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_videos', to='movies.moviesmodel')),
            ],
            options={
                'verbose_name': 'ویدیوی فیلم',
                'verbose_name_plural': 'ویدیوهای فیلم',
                'ordering': ['-created_on'],
            },
        ),
    ]
