# Generated by Django 6.1 on 2026-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesmodel',
            old_name='Release_date',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت خرید'),
        ),
    ]
