# Generated by Django 6.1 on 2026-08-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_release_date_moviesmodel_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='beloved',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='محبوب'),
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='mostٰٰ_Viewed',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='پربازدید'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='price',
            field=models.PositiveBigIntegerField(default=0, help_text='براساس تومان', verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='عنوان فیلم'),
        ),
    ]
