# Generated by Django 6.1 on 2026-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviesmodel_beloved_moviesmodel_most__viewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesmodel',
            name='mostٰٰ_Viewed',
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='most_Viewed',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='پربازدید'),
        ),
    ]
