# Generated by Django 6.1 on 2026-09-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_moviesmodel_most_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
