# Generated by Django 6.1 on 2026-09-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_moviesmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='is_double',
            field=models.BooleanField(default=False, verbose_name='دوبله'),
        ),
    ]
