# Generated by Django 6.1 on 2026-09-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_moviesmodel_is_double'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesmodel',
            name='discount',
        ),
    ]
