# Generated by Django 6.1 on 2026-08-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='video_cart',
        ),
        migrations.AddField(
            model_name='user',
            name='purchased_movies',
            field=models.ManyToManyField(related_name='buyers', to='movies.moviesmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_by', to='movies.moviesmodel'),
        ),
    ]
