# Generated by Django 6.1 on 2026-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_video_cart_user_purchased_movies_and_more'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='purchased_movies',
            field=models.ManyToManyField(related_name='buyers', to='movies.moviesmodel', verbose_name='خریداری شده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_by', to='movies.moviesmodel', verbose_name='فیلم\u200cهای ذخیره\u200cشده'),
        ),
    ]
