# Generated by Django 6.1 on 2026-08-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_purchased_movies_alter_user_watchlist'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='purchased_movies',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='movies.moviesmodel', verbose_name='خریداری شده'),
        ),
    ]
