# Generated by Django 6.1 on 2026-09-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_purchased_movies'),
        ('movies', '0005_remove_moviesmodel_most_viewed_and_more'),
        ('payment', '0004_remove_movieownership_unique_user_movie_ownership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='purchased_movies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='MovieOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='movies.moviesmodel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='payment.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_ownership')],
            },
        ),
    ]
