# Generated by Django 6.1 on 2026-09-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_purchased_movies_remove_user_watchlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اشتراک')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدت اشتراک')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='special_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای ویژه'),
        ),
    ]
