# Generated by Django 6.1 on 2026-08-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userotpmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotpmodel',
            name='is_used',
        ),
    ]
