# Generated by Django 6.1 on 2026-08-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userotpmodel_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUserOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=32, verbose_name='نام کاربری')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('password', models.CharField(blank=True, max_length=32, null=True, verbose_name='پسورد')),
                ('code', models.PositiveIntegerField(verbose_name='کد تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد تایید ثبت نام',
                'verbose_name_plural': 'کدهای تایید ثبت نام',
                'ordering': ('-created_at',),
            },
        ),
    ]
