include /etc/nginx/conf.d/upstream.inc;

server {
    listen 80;
    server_name localhost;

    client_max_body_size 100M;


    include /etc/nginx/conf.d/locations.inc;
    include /etc/nginx/conf.d/errors.inc;
}