# Generated by Django 6.1 on 2026-08-30 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('expired', 'منقضی شده')], default='pending', max_length=20)),
                ('authority', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
