# Generated by Django 6.1 on 2026-08-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_release_date_moviesmodel_release_date_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.moviesmodel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='payment.payment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('payment', 'movie'), name='unique_movie_per_payment')],
            },
        ),
    ]
