# Generated by Django 6.1 on 2026-09-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_movieownership'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movieownership',
            name='unique_user_movie_ownership',
        ),
        migrations.DeleteModel(
            name='MovieOwnership',
        ),
    ]
