# Generated by Django 6.1 on 2026-09-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_movieownership_unique_user_movie_ownership_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.AlterModelOptions(
            name='paymentitem',
            options={'verbose_name': 'آیتم پرداخت', 'verbose_name_plural': 'آیتم های پرداخت'},
        ),
    ]
