# Generated by Django 6.1 on 2026-09-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment.coupon', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
    ]
