# Generated by Django 6.1 on 2026-09-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriptionplan_userprofile_special_expires_at'),
        ('payment', '0009_remove_coupon_user_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.subscriptionplan'),
        ),
    ]
